#!/usr/bin/env bash
sudo ifconfig lo0 alias 10.254.254.254
cd src && cd .. && \
docker-sync start && \
docker-compose up -d && \
docker cp -a sites-available/. magento2_apache_1:/etc/apache2/sites-available/
echo 'Virtual hosts updated!' && \
echo '
===================== 🚀 Done 🚀 ===================

      IMAGINATION MEDIA (https://www.imaginemage.com/)

      🌎 Web server: http://localhost/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================='